//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faculdade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int id_client { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string cpf { get; set; }
        public string sexo { get; set; }
        public string phone { get; set; }
        public string cnh { get; set; }
        public string registroCnh { get; set; }
        public string validadeCnh { get; set; }
        public string categoriaCnh { get; set; }
        public string ufCnh { get; set; }
        public string rg { get; set; }
        public string nascimento { get; set; }
        public string logradouro { get; set; }
        public string cep { get; set; }
        public string numero { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
    }
}
