//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faculdade.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rentacarEntities : DbContext
    {
        public rentacarEntities()
            : base("name=rentacarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Features> Features { get; set; }
        public virtual DbSet<Fleets> Fleets { get; set; }
        public virtual DbSet<Fuels> Fuels { get; set; }
        public virtual DbSet<GroupsCar> GroupsCar { get; set; }
        public virtual DbSet<Models> Models { get; set; }
        public virtual DbSet<Rents> Rents { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
