//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faculdade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fleets
    {
        public int id_fleet { get; set; }
        public int groupCar_id { get; set; }
        public int feature_id { get; set; }
        public int model_id { get; set; }
        public int brand_id { get; set; }
        public string image { get; set; }
        public string board { get; set; }
        public bool status { get; set; }
        public int year { get; set; }
        public decimal daily { get; set; }
    }
}
