//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faculdade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fuels
    {
        public int id_fuel { get; set; }
        public string name { get; set; }
    }
}
