//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faculdade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rents
    {
        public int id_rent { get; set; }
        public int client_id { get; set; }
        public int fleet_id { get; set; }
        public int place_of_withdrawal_id { get; set; }
        public System.DateTime date_of_withdrawal { get; set; }
        public System.DateTime return_date { get; set; }
        public decimal amount { get; set; }
    }
}
